services:
  postgres:
    image: postgres:17-alpine
    container_name: ${PROJECT_NAME}_postgres
    env_file:
      - .envs/.postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-alpine
    container_name: ${PROJECT_NAME}_redis
    command: --port 6379
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: