#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd /app/app

python manage.py tailwind install
python manage.py tailwind build

python manage.py collectstatic --clear --noinput

python manage.py migrate

gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4