#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd /app/app

# Remove any existing beat schedule file
rm -f ./celerybeat.pid
rm -f ./celerybeat-schedule

celery -A config beat --loglevel=info --scheduler=django_celery_beat.schedulers:DatabaseScheduler --uid=1000 --gid=1000 